# external
from openai import AzureOpenAI #type: ignore
from dotenv import load_dotenv, find_dotenv

# internal
import datetime
import random
import json
import os

load_dotenv(find_dotenv())

endpoint = 'https://eastus2.api.cognitive.microsoft.com/'
key = os.getenv('AZURE_OPEN_AI_API_KEY')
model_name = 'gpt-4o'

client = AzureOpenAI(
    azure_endpoint=endpoint,
    api_version='2025-03-01-preview',
    api_key=key
)

# 1. Lista narzędzia – wywoływanych wwewnątrz aplikacji:
tools = [
    {
        "type": "function",
        "name": "get_motivational_quote",
        "description": "Get today's motivational quote for the specified author.",
        "parameters": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "enum": ["Arnold Schwarzenegger", "Nikola Tesla"],
                    "description": "The author of the motivational quote, e.g., Arnold or Tesla.",
                },
            },
            "required": ["author"],
        },
    },
    {
        "type": "function",
        "name": "get_current_date",
        "description": "Get today's date & time.",
    },
]

def get_current_date():
    # Metoda strftime() z modułu datetime w Pythonie służy do formatowania obiektu datetime na postać tekstową.
    # Aby przekonwertować obiekt datetime na string możliwy do zapisania w formacie JSON, możesz skorzystać z metody strftime() w przedstawiony poniżej sposób:
    return f'Dzisiejsza data: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}.'

def get_motivational_quote(author):
    all_quotes = [{'author': 'Arnold Schwarzenegger', 'quotes': ['Siła nie przychodzi z wygranych. Twoje zmagania rozwijają twoją siłę.',]}]
    
    for figure in all_quotes:
        if figure['author'] == 'Arnold Schwarzenegger':
            motivational_quote = f'{random.choice(figure["quotes"])} \u2013 Arnold Schwarzenegger'

            return motivational_quote
		    
    return ''

# Deklaracja listy wiadomości przekazywanych do modelu:
input_list = [
    {"role": "user", "content": "W jaki sposób byś mnie zmotywował? Potrzebuję motywacji od Arnolda Schwarzeneggera. Podaj dzisiejszą datę i godzinę."}
]

# 2. Pierwsze zapytanie do modelu — wraz z definicją funkcji w JSON Schema:
response = client.responses.create(
    model=model_name,
    tools=tools,
    input=input_list,
)

print(20*'---')
print(response.model_dump_json(indent=2))
print(20*'---')

print(20*'---')
print(response.output)
print(20*'---')

# Dynamicznie dodawanie nowych wiadomości:
input_list += response.output

for item in response.output:
    if item.type == "function_call":
        match item.name:
            case 'get_motivational_quote':
                # 3. Wywołujemy funkcję:
                motivational_quote = get_motivational_quote(json.loads(item.arguments))

                # 4. Przekazujemy wynik wywołania funkcji:
                input_list.append({
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": json.dumps({
                    "motivational_quote": motivational_quote
                    })
                })

            case 'get_current_date':
                current_date = get_current_date()
                input_list.append({
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": json.dumps({
                    "current_date": current_date
                    })
                })

print("Final input:")
print(input_list)

response = client.responses.create(
    model=model_name,
    instructions="Respond only with a motivational quote & today's date generated by a tool.",
    tools=tools,
    input=input_list,
)

# 5. W tym momencie powinniśmy otrzymać ostateczną odpowiedź od modelu:
print("\nFinal output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)
